### ISSUE TITLE
Replace `ms-air-aiagility...` with AzureCLI tasks

### ISSUE THREAD

**Issue by epa095** [microsoft/MLOpsPython#291]
In https://github.com/microsoft/MLOpsPython/blob/master/.pipelines/diabetes_regression-ci.yml there are now 3 places where some tasks starting with `ms-air-aiagility.`, and those are:
- `ms-air-aiagility.vss-services-azureml.azureml-restApi-task.MLPublishedPipelineRestAPITask@0`
- `ms-air-aiagility.vss-services-azureml.azureml-model-deploy-task.AMLModelDeploy@0` (used twice)

These are available when one installs the azure machine learning extension into azure devops. The alternative to using these tasks is to use the `AzureCLI@2` task in combination with `az ml...`. There are some issues with using the ms-air-aiagility tasks:
- They are not documented anywhere. This repo is pretty much the only use I can find of them, and one has to guess what they do.
- They make it very hard to debug a pipeline by manually re-doing the steps.
- They can not be used in other CI tools like e.g.  (the Microsoft owned) github actions.

One place where the alternative approach (`az ml ...`) is used is [this](https://github.com/MicrosoftDocs/pipelines-azureml/blob/master/pipelines/diabetes-train-and-deploy.yml) Microsoft repository. 

As an example, I have replaced the ACI call to `ms-air-aiagility.vss-services-azureml.azureml-model-deploy-task.AMLModelDeploy@0` with the following code:

```
    - task: AzureCLI@2
      displayName: 'Invoke and monitor ML pipeline'
      inputs:
        azureSubscription: '$(AZURE_RM_SVC_CONNECTION)'
        scriptLocation: inlineScript
        scriptType: 'bash'
        workingDirectory: '$(Build.SourcesDirectory)/$(SOURCES_DIR_TRAIN)/scoring'
        inlineScript: |
          az extension add -n azure-cli-ml
          az ml folder attach -w $(WORKSPACE_NAME) -g $(RESOURCE_GROUP)
          az ml model deploy  -n $(ACI_DEPLOYMENT_NAME) --model $(MODEL_NAME):$(MODEL_VERSION) --ic $(Build.SourcesDirectory)/$(SOURCES_DIR_TRAIN)/scoring/inference_config.yml --dc $(Build.SourcesDirectory)/$(SOURCES_DIR_TRAIN)/scoring/deployment_config_aci.yml -g $(RESOURCE_GROUP) -w $(WORKSPACE_NAME) --overwrite
```

The other task, `MLPublishedPipelineRestAPITask` is a bit more work to replace, since it waits for the pipeline to complete, and I did not find a direct `az` command to do the same (so I had to write a bash loop). But that is good incentive for you guys (Microsoft) to add a `--wait-for-completion` flag to `az ml run submit-pipeline` ;-)
