### ISSUE TITLE
Trigger ML Training Pipeline failed

### ISSUE THREAD

**Issue by xlegend1024** [microsoft/MLOpsPython#299]
A job ' Invoke ML pipeline' failed in 'Train model' stage with following error messages.

URL https://.aether.ms/api/v1.0/subscriptions/256c7222-4083-4ba7-8714-baa0df54bfe6/resourceGroups//providers/Microsoft.MachineLearningServices/workspaces//PipelineRuns/PipelineSubmit/3a04d8d2-d2d8-4c37-8dc1-05bbe8ac44e3 for HttpRequest is not correct.

The URL that shown on the error seems missing location in the address. How can i fix this?

**Comment by jonathanneo** [comment]
I have a similar issue: 

`URL https://Australia East.aether.ms/api/v1.0/subscriptions/451b6b03-be52-48aa-9baf-e54c858fd485/resourceGroups/DEV-TLP-AML-RG/providers/Microsoft.MachineLearningServices/workspaces/DEV-TLP-mlops-AML-WS/PipelineRuns/PipelineSubmit/b339b843-60b0-4a2e-b3b0-39da01fe6889 for HttpRequest is not correct.`

It is appending the region at the front as `Australia East` instead of `australiaeast`.

**Comment by j-so** [comment]
We are investigating this issue. Thank you for reporting this

**Comment by jonathanneo** [comment]
Please note that the task in which this fails is when it uses the ms-air-aiagility task.

**Comment by xlegend1024** [comment]
@jonathanneo 

A job **'Invoke ML pipeline'** failed in **'Train model' stage** in **[.pipelines/diabetes_regression-ci.yml](https://github.com/microsoft/MLOpsPython/blob/master/.pipelines/diabetes_regression-ci.yml)** with following error messages.

``
URL https://.aether.ms/api/v1.0/subscriptions/256c7222-4083-4ba7-8714-baa0df54bfe6/resourceGroups//providers/Microsoft.MachineLearningServices/workspaces//PipelineRuns/PipelineSubmit/3a04d8d2-d2d8-4c37-8dc1-05bbe8ac44e3 for HttpRequest is not correct.
``

**Comment by jonathanneo** [comment]
@xlegend1024 Yep, mine failed at exactly where yours did too. 

I believe it is to do with the `ms-air-aiagility` task. 

Here is the section of `.pipelines\diabetes_regression-ci.yml` where the error occurred: 
```yaml
- job: "Run_ML_Pipeline"
    dependsOn: "Get_Pipeline_ID"
    displayName: "Trigger ML Training Pipeline"
    timeoutInMinutes: 0
    pool: server
    variables:
      AMLPIPELINE_ID: $[ dependencies.Get_Pipeline_ID.outputs['getpipelineid.AMLPIPELINEID'] ]
    steps:
    - task: ms-air-aiagility.vss-services-azureml.azureml-restApi-task.MLPublishedPipelineRestAPITask@0
      displayName: 'Invoke ML pipeline'
      inputs:
        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
        PipelineId: '$(AMLPIPELINE_ID)'
        ExperimentName: '$(EXPERIMENT_NAME)'
        PipelineParameters: '"ParameterAssignments": {"model_name": "$(MODEL_NAME)"}, "tags": {"BuildId": "$(Build.BuildId)", "BuildUri": "$(BUILD_URI)"}, "StepTags": {"BuildId": "$(Build.BuildId)", "BuildUri": "$(BUILD_URI)"}'
```
